### ISSUE TITLE
speckle_exe Konsolenausgabe

### ISSUE THREAD

**Issue by smiddy** [smiddy/speckleCorrelation#27]
Hallo Andreas,
ich habe deine Code v1.0.0 laufen lassen (ohne deine Erklaerung zu lesen ;-) ) und soweit funktioniert es! Ich bin nur irritiert ueber die Ausgabe der speckle_exe:

**************************************************************
Add imposed X and Y displacements to matrix "results" before
continuing. Execute the last two sections of the script
speckle_exe.m manually to plot results!
**************************************************************

Warum soll ich noch Verschiebungen hinzufuegen?

heisst dass, ich muss noch andere skripte ausfuehren? Und warum soll ich noch teile eines Skriptes manuell ausfuehren, wenn ich die plots schon alle sehe?

**Comment by aruebe** [comment]
Hallo Markus
Danke für dein Feedback. Freut mich, dass es funktioniert hat (und auch selbsterklärend ist :) )

Mit "imposed X and Y displacements" sind die mit den Controllern vorgegebenen Verschiebungen gemeint, die ich im Lab vorgegeben habe. Um bei grösseren Datenmengen anschliessend z.B. diesen Plot

![shiftplotpix](https://cloud.githubusercontent.com/assets/8830484/6635308/d1256cd8-c964-11e4-83a3-e28d8c88ecda.png)

auszugeben, brauche ich die Daten. Und diese kann der Code nicht wissen, also muss ich sie noch eingeben bevor in den letzten zwei Abschnitten des Codes *speckle_exe.m* diese Plots generiert werden können.

(Und während ich diese Sätez schreibe, fällt mir ein, dass ich das ja nur gemacht habe um den Code zu testen und das kein fester Bestandteil des Programms sein sollte. Ein Nutzer ist ja nur daran interessiert, jeweils ein einziges Bild zu korrigieren :/ )

**Comment by aruebe** [comment]
Was schlägst du vor.. Sollten diese Passagen entfernt werden?

**Comment by aruebe** [comment]
Weitere Skripts müssen nicht mehr ausgeführt werden.

Und das ist richtig, die relevanten Plots siehst du schon. Die noch zu generierenden Plots sind meine Auswertung aller Testfiles, die ich im Lab gemacht habe. Deshalb soll man weitere Teile des Skriptes manuell ausführen. Verwirrend für einen Anwender..das sehe ich jetzt.

**Comment by smiddy** [comment]
Das kannst du machen. Oder allenfalls in ein separates Skript transferieren, welches dann zum testen/debuggen gedacht ist. Dann geht der code nicht verloren

**Comment by aruebe** [comment]
In Ordnung, das macht meiner Meinung nach auch Sinn die Zeilen aus dem Skript zu nehmen. 

Ich hoffe, ich kriege mit dem entfernten Code-Teil so schnell ein Skript gemacht, welches ich (einem neuen Release?) beifügen kann. Werde es probieren!

**Comment by smiddy** [comment]
Genau, mache nach deinen Aenderungen einen neuen Release

**Comment by aruebe** [comment]
So, ich habe mich dahinter gesetzt und hoffe, dass ich einen guten Weg gefunden habe, das Post-Processing auszulagern.
