### ISSUE TITLE
speckle_exe matrix 'result'

### ISSUE THREAD

**Issue by smiddy** [smiddy/speckleCorrelation#28]
In der speckle_exe ist nicht beschrieben, welche results in welcher Einheit dort gespeichert werden. Bei mir schaut es so aus:

NaN	NaN	0.0572156096756675	0.00330438638446760	NaN
NaN	NaN	0.0654529352867723	0.00403289721949847	NaN

Was haben die Werte zu bedeuten?

**Comment by aruebe** [comment]
Stimmt, dass ist nicht beschrieben. 

Die NaN Werte wären eben noch manuell zu ergänzen. Das sind die "Imposed X and Y displacements" und der letzte NaN der vorgegebene Winkel, sofern möglich. Bei mir war das nur eine fortlaufende Zahl.

Kann ich bereinigen, wenn ich *speckle_exe.m* anpasse.

**Comment by smiddy** [comment]
Wichtig ist einfach, dass ich nachvollziehen kann, wie die Einträge definiert sind.

**Comment by aruebe** [comment]
Korrigiert mit letztem Commit 410e91b85ef68f7541c693303432ed5a98897d4a.
